[mysqld]
port=3306
datadir="C:\\Users\\Asus\\Desktop\\Billing-Suite-Electron\\.mysql_data"
secure_file_priv=""
tmpdir="C:\\Users\\Asus\\Desktop\\Billing-Suite-Electron\\.mysql_data"
default_authentication_plugin=mysql_native_password
